steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'cloudrunservice'
    - '--image'
    - 'northamerica-northeast2-docker.pkg.dev/automatic-bot-376307/continuus/continuus'
    - '--region'
    - 'northamerica-northeast2'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'