steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - '$BRANCH_NAME'
    - '--image'
    - 'northamerica-northeast2-docker.pkg.dev/automatic-bot-376307/continuus/$BRANCH_NAME-prod'
    - '--region'
    - 'northamerica-northeast2'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    secretEnv: ['NEXTAUTH_URL', 'NEXTAUTH_SECRET', 'GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_SECRET']
availableSecrets:
  secretManager:
  - versionName: projects/871909765266/secrets/$BRANCH_NAME-NEXTAUTH_URL/versions/1
    env: 'NEXTAUTH_URL'
  - versionName: projects/871909765266/secrets/$BRANCH_NAME-NEXTAUTH_SECRET/versions/1
    env: 'NEXTAUTH_SECRET'
  - versionName: projects/871909765266/secrets/$BRANCH_NAME-GOOGLE_CLIENT_ID/versions/1
    env: 'GOOGLE_CLIENT_ID'
  - versionName: projects/871909765266/secrets/$BRANCH_NAME-GOOGLE_CLIENT_SECRET/versions/1
    env: 'GOOGLE_CLIENT_SECRET'

options:
  logging: CLOUD_LOGGING_ONLY