steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "northamerica-northeast2-docker.pkg.dev/automatic-bot-376307/continuus/$BRANCH_NAME-sql-proxy", "docker/prod/migrate/."]

  - name: "northamerica-northeast2-docker.pkg.dev/automatic-bot-376307/continuus/$BRANCH_NAME-sql-proxy"
    dir: /
    env:
      - "DATABASE_URL=postgresql://postgres:continuus@localhost/$BRANCH_NAME?host=/cloudsql/automatic-bot-376307:us-central1:postgres"
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        /cloudsql/cloud-sql-proxy --unix-socket /cloudsql automatic-bot-376307:us-central1:postgres & sleep 2;
        npx prisma migrate prod

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - '$BRANCH_NAME'
    - '--image'
    - 'northamerica-northeast2-docker.pkg.dev/automatic-bot-376307/continuus/$BRANCH_NAME-prod'
    - '--region'
    - 'northamerica-northeast2'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--set-secrets'
    - 'DATABASE_URL=projects/871909765266/secrets/$BRANCH_NAME-DATABASE_URL/versions/latest,NEXTAUTH_URL=projects/871909765266/secrets/$BRANCH_NAME-NEXTAUTH_URL/versions/latest,NEXTAUTH_SECRET=projects/871909765266/secrets/$BRANCH_NAME-NEXTAUTH_SECRET/versions/latest,GOOGLE_CLIENT_ID=projects/871909765266/secrets/$BRANCH_NAME-GOOGLE_CLIENT_ID/versions/latest,GOOGLE_CLIENT_SECRET=projects/871909765266/secrets/$BRANCH_NAME-GOOGLE_CLIENT_SECRET/versions/latest'
options:
  logging: CLOUD_LOGGING_ONLY