#!/bin/bash

# $1: Cloud Build Trigger ID
# $2: Branch Name
# $3: Stage Name

trigger_output=$(gcloud builds triggers run $1 --branch=$2 --format="json")

build_id=$(echo $trigger_output | jq -r '.metadata."build"."id"')
log_url=$(echo $trigger_output | jq -r '.metadata."build"."logUrl"')

echo "$3 stage started for branch $2"
echo "Google Cloud Build ID: $build_id"
echo "Logs: $log_url"

status="WORKING"
i=0

while [[ $status == "WORKING" || $status == "QUEUED" && $i -lt 900 ]]; do
  sleep 10
  describe_output=$(gcloud builds describe $build_id --format="json")
  status=$(echo $describe_output | jq -r '.status')
  echo "Build status: $status. Waiting 10 seconds..."
  let "i+=1"
done

if [[ "$3" == *"Test"* ]]; then
  echo "Test results:"
  gcloud builds log "$build_id" | grep -o "Step #1:.*" | cut -f2- -d:
fi

if [[ $status == "SUCCESS" ]]; then
  echo "Build succeeded!"
  if [[ $3 == "Deploy" ]]; then
    gcloud builds log "$build_id" | grep "Service URL"
  fi
  exit 0
elif [[ $status == "FAILED" ]]; then
  echo "Build failed. See logs: $log_url"
else
  echo "Build failed (status $status). Check build logs: $log_url"
fi

exit 1
