#!/bin/bash

trigger_output=$(gcloud beta builds triggers run $1 --branch=$2 --format="json")

build_id=$(echo $trigger_output | jq -r '.metadata."build"."id"')
log_url=$(echo $trigger_output | jq -r '.metadata."build"."logUrl"')

echo "build id: $build_id"
echo "log url: $log_url"

status="WORKING"
i=0

while [[ $status == "WORKING" && $i -lt 30 ]]; do
  sleep 10
  describe_output=$(gcloud beta builds describe $build_id --format="json")
  status=$(echo $describe_output | jq -r '.status')
  echo "Build status: $status. Waiting 10 seconds..."
  let "i+=1"
done

if [[ $status == "SUCCESS" ]]; then
  echo "Build succeeded"
  exit 0
elif [[ $status == "FAILED" ]]; then
  echo "Build failed. See logs: $log_url"
else
  echo "Build failed (status $status). Check build logs: $log_url"
fi

exit 1
