
# https://medium.com/devops-techable/github-actions-and-google-cloud-build-triggers-d55aceb96e68 
name: GCP Cloud Build, Test and Deploy

on:
  push:
    branches: 
    - dev
    - qa
    - prod

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - name: 'Start Google Cloud Build trigger'
      run: |
        export CLOUDSDK_CORE_DISABLE_PROMPTS=1
        chmod +x ./scripts/wait-for-build
        ./scripts/wait-for-build ${{ secrets.GCP_BUILD_BUILD_ID }} ${GITHUB_REF##*/} Build
  
  unit-test:
    name: Test (Unit)
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v3
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - name: 'Start Google Cloud Build trigger'
      run: |
        export CLOUDSDK_CORE_DISABLE_PROMPTS=1
        chmod +x ./scripts/wait-for-build
        ./scripts/wait-for-build ${{ secrets.GCP_BUILD_TEST_ID }} ${GITHUB_REF##*/} "Test (Unit)"

  integration-test:
    name: Test (Integration)
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v3
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - name: 'Start Google Cloud Build trigger'
      run: |
        export CLOUDSDK_CORE_DISABLE_PROMPTS=1
        chmod +x ./scripts/wait-for-build
        ./scripts/wait-for-build ${{ secrets.GCP_BUILD_TEST_ID }} ${GITHUB_REF##*/} "Test (Integration)"

  coverage-test:
    name: Test (Coverage)
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v3
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - name: 'Start Google Cloud Build trigger'
      run: |
        export CLOUDSDK_CORE_DISABLE_PROMPTS=1
        chmod +x ./scripts/wait-for-build
        ./scripts/wait-for-build ${{ secrets.GCP_BUILD_TEST_ID }} ${GITHUB_REF##*/} "Test (Coverage)"

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [unit-test, integration-test, coverage-test]
    steps:
    - uses: actions/checkout@v3
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - name: 'Start Google Cloud Build trigger'
      run: |
        export CLOUDSDK_CORE_DISABLE_PROMPTS=1
        chmod +x ./scripts/wait-for-build
        ./scripts/wait-for-build ${{ secrets.GCP_BUILD_DEPLOY_ID }} ${GITHUB_REF##*/} Deploy

  cleanup:
    name: Cleanup Test Artifacts
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v3
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Set outputs
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - name: 'Start Google Cloud Build trigger'
      run: |
        export CLOUDSDK_CORE_DISABLE_PROMPTS=1
        chmod +x ./scripts/wait-for-build
        gcloud artifacts docker images delete northamerica-northeast2-docker.pkg.dev/automatic-bot-376307/continuus/${{ steps.vars.outputs.sha_short }}-test --delete-tags

